PeruTourism/Controllers/PagoVisaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using PeruTourism.Repository.PeruTourism;
using PeruTourism.Models.Visa;

namespace PeruTourism.Controllers
{
    public class PagoVisaController : Controller
    {

        PagoVisaAccess objPagoVisaAccess = new PagoVisaAccess();
        PedidoVisaViewModel objPedidoVisaViewModel = new PedidoVisaViewModel();
        // GET: PagoVisa
        //public ActionResult Index()
        //{
        //    return View();
        //}
        //public ActionResult Pago(string pIdPedido, string pcodCliente, string pNroPrograma, string pFlagIdioma, bool pFlagVendido) {

        //    string sIdPedido = string.Empty;

        //    string urlPago = string.Empty;

        //    urlPago = objPagoVisaAccess.CargaUrlVisanetLink();

        //    objPedidoVisaViewModel.urlPago = urlPago;
        //    objPedidoVisaViewModel.codCliente = pcodCliente;
        //    objPedidoVisaViewModel.idPedido = pIdPedido;
        //    objPedidoVisaViewModel.nroPrograma = pNroPrograma;
        //    objPedidoVisaViewModel.idioma = pFlagIdioma;
        //    objPedidoVisaViewModel.flagVendido = pFlagVendido;

        //    int sIdPedido_length = sIdPedido.Length;

        //    return View(objPedidoVisaViewModel);


        //}
        //public ActionResult ConfirmarPago(PedidoVisa pedido) {

        //    var lstPedidoVisa = objPagoVisaAccess.CargarPedidoVisa(Convert.ToInt32(pedido.IDPedido.Substring(13, 6)));



        //    objPedidoVisaViewModel.lstPedidoVisa = lstPedidoVisa.ToList();

        //    return View(objPedidoVisaViewModel);

        //}

        //public ActionResult RealizarPago(PedidoVisa pedido) {


        //    var lstPedidoVisa = new List<PedidoVisa>();

        //    lstPedidoVisa.Add(item: pedido);

        //    if (!ModelState.IsValid) {

        //        objPedidoVisaViewModel.lstPedidoVisa = lstPedidoVisa;

        //        //string gg = objPagoVisaAccess.InsertarOrdenpagoVISA(pedido.Monto, pedido.IDPedido);
        //        return View("~/Views/PagoVisa/Pago.cshtml", objPedidoVisaViewModel);
        //    }

        //    string gg = objPagoVisaAccess.InsertarOrdenpagoVISA(pedido.Monto, pedido.IDPedido);
        //    return Content("Success");
        //}



	}
}

PeruTourism/Views/PagoVisa/ConfirmarPago.cshtml
@model PeruTourism.Models.Visa.PedidoVisaViewModel
@using PeruTourism.Utility
@{
    ViewBag.Title = "ConfirmarPago";
    var lstPedidoVisa = Model.lstPedidoVisa;

    var IDPedido = lstPedidoVisa.FirstOrDefault().IDPedido;

    var lajaxOptionsForm = new AjaxOptions()
    {
        HttpMethod = "POST",
        OnBegin = "e_ajax_iniciando",
        OnComplete = "e_ajax_finalizando_form_ficha",
        OnFailure = "e_ajax_error"
    };
}

<h2>ConfirmarPago</h2>

<div id="propDet" class="secondary">

    @*<form id="formPagoVisa">*@

    @using (Ajax.BeginForm("RealizarPago", "PagoVisa", null, lajaxOptionsForm, new { @id = "form-pagoVisa", @class = "well form-horizontal" }))
    {

        <input type="hidden" id="IDPedido" value="@IDPedido.Trim()" />

        <div class="form-group">
            <label for="email">A favor de:</label>
            <label for="email">VIAJES PENTAGRAMA</label>

        </div>
        <div class="form-group">
            <label for="email">Cliente:</label>
            <label for="email">@lstPedidoVisa.FirstOrDefault().NomCliente</label>

        </div>
        <div class="form-group">
            <label for="email">Servicio:</label>
            <label for="email">@lstPedidoVisa.FirstOrDefault().DesPedido</label>

        </div>
        <div class="form-group">
            <label for="pwd">Monto a pagar:</label>
            @*<input type="number" class="form-control" id="monto">*@
            @Html.TextBoxFor(c => Model.lstPedidoVisa.FirstOrDefault().Monto, new { @class = "form-control" })
            @Html.TextBoxFor(c => Model.lstPedidoVisa.FirstOrDefault().IDPedido, new { @class = "form-control", @Value = IDPedido.Trim(), @type = "hidden" })
        </div>
        @*<div class="checkbox">
                <label><input type="checkbox"> Acepta</label>
            </div>*@
        <button type="submit" class="pago">Realizar Pago</button>

        <button type="submit" class="pago">Corregir Monto</button>
        <a class="pago">Realizar Pago</a>

    }


</div>

PeruTourism/Views/PagoVisa/Info.cshtml
@{
    ViewBag.Title = "Info";
}

<h2>Info</h2>

PeruTourism/Views/PagoVisa/_ModalCondicionesPago.cshtml
<div class="group prop-detalle">
    <div class="group group-collapse collapsed" data-toggle="collapse" data-target="#content1">
        <div class="prop-num"><span></span></div>
        <div class="prop-title">Payment Procedure</div>
    </div>
    <div class="prop-content collapse in" id="content1">
        <div class="group">

            <ul>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>

            </ul>
        </div>
    </div>
    <div class="prop-icon"></div>
</div>

<div class="group prop-detalle">
    <div class="group group-collapse collapsed" data-toggle="collapse" data-target="#content1">
        <div class="prop-num"><span></span></div>
        <div class="prop-title">Our Cancellation Policy</div>
    </div>
    <div class="prop-content collapse in" id="content1">
        <div class="group">

            <ul>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>
                <li>Condicion 1</li>

            </ul>
        </div>
    </div>
    <div class="prop-icon"></div>
</div>